export const majorArcana = [
    { name: 'The Fool', numeral: '0', meaning: 'New beginnings, spontaneity, and a free spirit. Trust the journey ahead.', emoji: '🌟', keywords: ['Beginnings', 'Free Spirit', 'Innocence'], element: 'Air', planet: 'Uranus' },
    { name: 'The Magician', numeral: 'I', meaning: 'Manifestation, resourcefulness, and power. You have all the tools you need.', emoji: '✨', keywords: ['Power', 'Skill', 'Action'], element: 'Air', planet: 'Mercury' },
    { name: 'The High Priestess', numeral: 'II', meaning: 'Intuition, sacred knowledge, and the subconscious mind. Trust your inner voice.', emoji: '🌙', keywords: ['Intuition', 'Mystery', 'Subconscious'], element: 'Water', planet: 'Moon' },
    { name: 'The Empress', numeral: 'III', meaning: 'Abundance, nurturing, and fertility. Nature and beauty surround you.', emoji: '🌺', keywords: ['Fertility', 'Nature', 'Abundance'], element: 'Earth', planet: 'Venus' },
    { name: 'The Emperor', numeral: 'IV', meaning: 'Authority, structure, and fatherhood. Take control of your life.', emoji: '👑', keywords: ['Authority', 'Structure', 'Control'], element: 'Fire', planet: 'Mars' },
    { name: 'The Hierophant', numeral: 'V', meaning: 'Tradition, conformity, and spiritual guidance. Seek wisdom from established systems.', emoji: '⛪', keywords: ['Tradition', 'Guidance', 'Conformity'], element: 'Earth', planet: 'Venus' },
    { name: 'The Lovers', numeral: 'VI', meaning: 'Love, harmony, and relationships. Alignment of values and choices.', emoji: '💕', keywords: ['Love', 'Union', 'Choices'], element: 'Air', planet: 'Mercury' },
    { name: 'The Chariot', numeral: 'VII', meaning: 'Control, willpower, and victory. Assert yourself and conquer.', emoji: '🐎', keywords: ['Victory', 'Willpower', 'Control'], element: 'Water', planet: 'Moon' },
    { name: 'Strength', numeral: 'VIII', meaning: 'Strength, courage, and persuasion. You have inner power.', emoji: '🦁', keywords: ['Courage', 'Patience', 'Compassion'], element: 'Fire', planet: 'Sun' },
    { name: 'The Hermit', numeral: 'IX', meaning: 'Soul-searching, introspection, and being alone. Look within for answers.', emoji: '🕯️', keywords: ['Introspection', 'Solitude', 'Guidance'], element: 'Earth', planet: 'Mercury' },
    { name: 'Wheel of Fortune', numeral: 'X', meaning: 'Change, cycles, and inevitable fate. The wheel turns in your favor.', emoji: '🎡', keywords: ['Luck', 'Karma', 'Cycles'], element: 'Fire', planet: 'Jupiter' },
    { name: 'Justice', numeral: 'XI', meaning: 'Justice, fairness, and truth. Cause and effect are at play.', emoji: '⚖️', keywords: ['Justice', 'Truth', 'Law'], element: 'Air', planet: 'Venus' },
    { name: 'The Hanged Man', numeral: 'XII', meaning: 'Pause, surrender, and letting go. A new perspective is needed.', emoji: '🦇', keywords: ['Surrender', 'Perspective', 'Sacrifice'], element: 'Water', planet: 'Neptune' },
    { name: 'Death', numeral: 'XIII', meaning: 'Endings, change, and transformation. Clear the way for the new.', emoji: '💀', keywords: ['Endings', 'Change', 'Transformation'], element: 'Water', planet: 'Pluto' },
    { name: 'Temperance', numeral: 'XIV', meaning: 'Balance, moderation, and patience. Find the middle path.', emoji: '🍷', keywords: ['Balance', 'Moderation', 'Patience'], element: 'Fire', planet: 'Jupiter' },
    { name: 'The Devil', numeral: 'XV', meaning: 'Shadow self, attachment, and addiction. Break free from chains.', emoji: '😈', keywords: ['Addiction', 'Materialism', 'Playfulness'], element: 'Earth', planet: 'Saturn' },
    { name: 'The Tower', numeral: 'XVI', meaning: 'Sudden change, upheaval, and chaos. Foundations are shaken.', emoji: '⚡', keywords: ['Disaster', 'Upheaval', 'Sudden Change'], element: 'Fire', planet: 'Mars' },
    { name: 'The Star', numeral: 'XVII', meaning: 'Hope, faith, and rejuvenation. A guiding light shines upon your path.', emoji: '⭐', keywords: ['Hope', 'Faith', 'Rejuvenation'], element: 'Air', planet: 'Uranus' },
    { name: 'The Moon', numeral: 'XVIII', meaning: 'Illusion, fear, and the subconscious. Look beyond the surface.', emoji: '🌕', keywords: ['Illusion', 'Fear', 'Subconscious'], element: 'Water', planet: 'Neptune' },
    { name: 'The Sun', numeral: 'XIX', meaning: 'Joy, success, and vitality. Positivity radiates around you today.', emoji: '☀️', keywords: ['Positivity', 'Fun', 'Warmth'], element: 'Fire', planet: 'Sun' },
    { name: 'Judgement', numeral: 'XX', meaning: 'Judgement, rebirth, and inner calling. Rise up to a higher level.', emoji: '🎺', keywords: ['Judgement', 'Rebirth', 'Inner Calling'], element: 'Fire', planet: 'Pluto' },
    { name: 'The World', numeral: 'XXI', meaning: 'Completion, achievement, and travel. A cycle reaches its fulfillment.', emoji: '🌍', keywords: ['Completion', 'Integration', 'Accomplishment'], element: 'Earth', planet: 'Saturn' },
];

export const minorArcana = [
    { name: 'Ace of Swords', numeral: 'A', meaning: 'Breakthroughs, clarity, and new ideas.', emoji: '⚔️' },
    { name: 'Two of Swords', numeral: 'II', meaning: 'Difficult choices, indecision, and stalemate.', emoji: '⚔️' },
    { name: 'Three of Swords', numeral: 'III', meaning: 'Heartbreak, emotional pain, and sorrow.', emoji: '💔' },
    { name: 'Ace of Cups', numeral: 'A', meaning: 'New love, overflowing emotions, and creativity.', emoji: '🏆' },
    { name: 'Ace of Pentacles', numeral: 'A', meaning: 'New opportunities, prosperity, and stability.', emoji: '💰' },
    { name: 'Ace of Wands', numeral: 'A', meaning: 'Inspiration, new passion, and bold energy.', emoji: '🔥' },
    { name: 'King of Cups', numeral: 'K', meaning: 'Emotional balance, compassion, and diplomacy.', emoji: '👑' },
    { name: 'Queen of Wands', numeral: 'Q', meaning: 'Confidence, determination, and social grace.', emoji: '💃' },
    { name: 'Knight of Pentacles', numeral: 'Kn', meaning: 'Efficiency, routine, and conservatism.', emoji: '🐴' },
    { name: 'Page of Swords', numeral: 'P', meaning: 'Curiosity, restlessness, and mental energy.', emoji: '🗡️' },
];
